# Generated by Django 4.2.24 on 2025-09-08 09:33

import core.datetimes.ad_datetime
import core.fields
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('date_valid_from', core.fields.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now)),
                ('date_valid_to', core.fields.DateTimeField(blank=True, db_column='DateValidTo', null=True)),
                ('replacement_uuid', models.UUIDField(blank=True, db_column='ReplacementUUID', null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], db_column='Status')),
                ('channel', models.SmallIntegerField(choices=[(0, 'rest-hook')], db_column='Channel')),
                ('endpoint', models.CharField(db_column='Endpoint', max_length=255)),
                ('headers', django_cryptography.fields.encrypt(models.TextField(blank=True, db_column='Headers', max_length=255, null=True))),
                ('criteria', models.JSONField(blank=True, db_column='Criteria', null=True)),
                ('expiring', models.DateTimeField(db_column='Expiring')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fhir_r4_subscription_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fhir_r4_subscription_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblFhirR4Subscription',
                'managed': True,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubscriptionNotificationResult',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notified_successfully', models.BooleanField()),
                ('notification_time', core.fields.DateTimeField(db_column='Expiring', default=core.datetimes.ad_datetime.AdDatetime.now)),
                ('error', models.TextField(blank=True, default=None, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_r4_notifications_sent', to='fhir_R4_subscription.subscription')),
            ],
            options={
                'db_table': 'tblFhirR4SubscriptionNotificationResult',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubscription',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('date_valid_from', core.fields.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now)),
                ('date_valid_to', core.fields.DateTimeField(blank=True, db_column='DateValidTo', null=True)),
                ('replacement_uuid', models.UUIDField(blank=True, db_column='ReplacementUUID', null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'inactive'), (1, 'active')], db_column='Status')),
                ('channel', models.SmallIntegerField(choices=[(0, 'rest-hook')], db_column='Channel')),
                ('endpoint', models.CharField(db_column='Endpoint', max_length=255)),
                ('headers', django_cryptography.fields.encrypt(models.TextField(blank=True, db_column='Headers', max_length=255, null=True))),
                ('criteria', models.JSONField(blank=True, db_column='Criteria', null=True)),
                ('expiring', models.DateTimeField(db_column='Expiring')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical subscription',
                'verbose_name_plural': 'historical subscriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
